# Generated by Django 5.0 on 2024-01-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodels',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
